type: S3
config:
  bucket: "org-observability-prometheus-metrics"
  endpoint: "s3.us-east-1.amazonaws.com"
  region: "us-east-1"
  access_key: ${AWS_ACCESS_KEY_ID}
  secret_key: ${AWS_SECRET_ACCESS_KEY}
